#include <iostream>
#include <vector>
#include <random>
#include <algorithm>
#include <chrono>
#include <iostream>
// Include the Boost header required for float_sort
#include <boost/sort/spreadsort/spreadsort.hpp>

using namespace std::chrono;

long long time_sort(int n, bool use_boost) {
    std::mt19937 gen(42);
    std::uniform_real_distribution<> dis(0, 1);
    std::vector<double> orig(n);
    for (int i = 0; i < n; ++i) orig[i] = dis(gen);
    
    std::vector<double> v(n);
    int iters = 2000;
    
    // Warmup
    for (int i = 0; i < 50; ++i) {
        std::copy(orig.begin(), orig.end(), v.begin());
        if (use_boost) {
            boost::sort::spreadsort::float_sort(v.begin(), v.end());
        } else {
            std::sort(v.begin(), v.end());
        }
    }

    auto start = high_resolution_clock::now();
    for (int i = 0; i < iters; ++i) {
        std::copy(orig.begin(), orig.end(), v.begin());
        if (use_boost) {
            boost::sort::spreadsort::float_sort(v.begin(), v.end());
        } else {
            std::sort(v.begin(), v.end());
        }
    }
    auto end = high_resolution_clock::now();
    return duration_cast<microseconds>(end - start).count();
}

int main() {
    int best_sort_thresh = 2048; // safe default meaning std::sort is used up to 2048
    std::vector<int> candidates = {256, 384, 512, 768, 1024, 1280, 1536, 2048};
    
    for (int n : candidates) {
        long long t_std = time_sort(n, false);
        long long t_boost = time_sort(n, true);
        if (t_boost < t_std) {
            best_sort_thresh = n;
            break; // Crossover point found
        }
    }
    
    std::cout << "#ifndef ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n";
    std::cout << "#define ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n\n";
    std::cout << "// Auto-generated by tools/tune_thresholds.cpp\n";
    std::cout << "constexpr size_t TUNED_SORT_BOOST_THRESHOLD = " << best_sort_thresh << ";\n";
    std::cout << "constexpr size_t TUNED_QN_EXACT_THRESHOLD = 64;\n\n";
    std::cout << "#endif // ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n";
    
    return 0;
}
