#include <iostream>
#include <vector>
#include <random>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <numeric>
#include <boost/sort/spreadsort/spreadsort.hpp>

using namespace std::chrono;

// Measure median time over multiple runs to reduce noise.
// Returns median elapsed microseconds for `iters` iterations of sorting n elements.
double time_sort_median(int n, bool use_boost, int iters, int runs) {
    std::mt19937 gen(42);
    std::uniform_real_distribution<> dis(0, 1);
    std::vector<double> orig(n);
    for (int i = 0; i < n; ++i) orig[i] = dis(gen);

    std::vector<double> v(n);

    // Warmup
    for (int i = 0; i < 100; ++i) {
        std::copy(orig.begin(), orig.end(), v.begin());
        if (use_boost)
            boost::sort::spreadsort::float_sort(v.begin(), v.end());
        else
            std::sort(v.begin(), v.end());
    }

    std::vector<double> timings(runs);
    for (int r = 0; r < runs; ++r) {
        auto start = high_resolution_clock::now();
        for (int i = 0; i < iters; ++i) {
            std::copy(orig.begin(), orig.end(), v.begin());
            if (use_boost)
                boost::sort::spreadsort::float_sort(v.begin(), v.end());
            else
                std::sort(v.begin(), v.end());
        }
        auto end = high_resolution_clock::now();
        timings[r] = static_cast<double>(duration_cast<nanoseconds>(end - start).count());
    }
    std::sort(timings.begin(), timings.end());
    return timings[runs / 2];
}

int main() {
    // Finer grid of candidate thresholds
    std::vector<int> candidates = {128, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096};

    // Adaptive iteration count: more iterations for small n (where each sort is fast)
    auto get_iters = [](int n) -> int {
        if (n <= 256)  return 5000;
        if (n <= 1024) return 2000;
        if (n <= 4096) return 500;
        return 200;
    };
    constexpr int RUNS = 5; // median of 5 runs per candidate

    // Require boost to be at least 5% faster to declare a crossover,
    // AND the advantage must hold at the next candidate size (confirmation).
    constexpr double MARGIN = 0.95; // boost must be < 95% of std to count

    int best_sort_thresh = 512; // conservative default
    for (size_t i = 0; i < candidates.size(); ++i) {
        int n = candidates[i];
        int iters = get_iters(n);
        double t_std   = time_sort_median(n, false, iters, RUNS);
        double t_boost = time_sort_median(n, true,  iters, RUNS);
        double ratio = t_boost / t_std;

        // Boost must be clearly faster (with margin)
        if (ratio < MARGIN) {
            // Confirm at the next size if available
            bool confirmed = true;
            if (i + 1 < candidates.size()) {
                int n2 = candidates[i + 1];
                int iters2 = get_iters(n2);
                double t_std2   = time_sort_median(n2, false, iters2, RUNS);
                double t_boost2 = time_sort_median(n2, true,  iters2, RUNS);
                confirmed = (t_boost2 / t_std2) < 1.0; // at least not slower at next size
            }
            if (confirmed) {
                best_sort_thresh = n;
                break;
            }
        }
    }

    std::cout << "#ifndef ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n";
    std::cout << "#define ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n\n";
    std::cout << "// Auto-generated by tools/tune_thresholds.cpp\n";
    std::cout << "#define TUNED_SORT_BOOST_THRESHOLD " << best_sort_thresh << "\n";
    std::cout << "#define TUNED_QN_EXACT_THRESHOLD 64\n\n";
    std::cout << "#endif // ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n";

    return 0;
}
