#include <iostream>
#include <vector>
#include <random>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <numeric>
#include <boost/sort/spreadsort/spreadsort.hpp>

using namespace std::chrono;

// Helper to get iterations based on sample size
int get_iters_for_n(size_t n) {
    if (n <= 256) return 5000;
    if (n <= 1024) return 2000;
    if (n <= 4096) return 500;
    return 200;
}

long long measure_once(size_t n, bool use_boost, std::mt19937& gen) {
    std::uniform_real_distribution<> dis(0, 1);
    std::vector<double> orig(n);
    for (size_t i = 0; i < n; ++i) orig[i] = dis(gen);
    
    std::vector<double> v(n);
    int iters = get_iters_for_n(n);
    
    // Warmup
    for (int i = 0; i < 100; ++i) {
        std::copy(orig.begin(), orig.end(), v.begin());
        if (use_boost)
            boost::sort::spreadsort::float_sort(v.begin(), v.end());
        else
            std::sort(v.begin(), v.end());
    }

    auto start = high_resolution_clock::now();
    for (int i = 0; i < iters; ++i) {
        std::copy(orig.begin(), orig.end(), v.begin());
        if (use_boost)
            boost::sort::spreadsort::float_sort(v.begin(), v.end());
        else
            std::sort(v.begin(), v.end());
    }
    auto end = high_resolution_clock::now();
    return duration_cast<nanoseconds>(end - start).count() / iters;
}

long long time_sort_median(size_t n, bool use_boost) {
    std::vector<long long> results;
    std::mt19937 gen(42);
    for (int i = 0; i < 5; ++i) {
        results.push_back(measure_once(n, use_boost, gen));
    }
    std::sort(results.begin(), results.end());
    return results[2]; // Median
}

int main() {
    // --- Tune sort_boost: std::sort → boost::spreadsort crossover ---
    size_t best_sort_thresh = 4096; // safe default
    std::vector<size_t> candidates = {128, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096};

    for (size_t i = 0; i < candidates.size(); ++i) {
        size_t n = candidates[i];
        long long t_std = time_sort_median(n, false);
        long long t_boost = time_sort_median(n, true);

        // Crossover if boost is at least 5% faster
        if (t_boost < (t_std * 0.95)) {
            // Confirmation at the next candidate size (if available)
            if (i + 1 < candidates.size()) {
                size_t next_n = candidates[i+1];
                long long next_std = time_sort_median(next_n, false);
                long long next_boost = time_sort_median(next_n, true);
                if (next_boost <= next_std) {
                    best_sort_thresh = n;
                    break;
                }
            } else {
                best_sort_thresh = n;
                break;
            }
        }
    }

    // --- Tune sort_tbb: boost::spreadsort → parallel sort crossover ---
    // Heuristic: parallel sort wins when per-element cost is high enough
    // to amortize TBB scheduling overhead (~10-50us).
    size_t best_tbb_thresh = 6144; // safe default
    std::vector<size_t> tbb_candidates = {4096, 6144, 8192, 12288, 16384, 24576, 32768};

    for (size_t n : tbb_candidates) {
        long long t_boost = time_sort_median(n, true);
        double ns_per_elem = static_cast<double>(t_boost) / static_cast<double>(n);
        // When per-element cost > 150ns, parallel overhead is amortized
        if (ns_per_elem > 150 && n >= 4096) {
            best_tbb_thresh = n;
            break;
        }
    }

    std::cout << "#ifndef ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n";
    std::cout << "#define ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n\n";
    std::cout << "// Auto-generated by tools/tune_thresholds.cpp\n";
    std::cout << "#define TUNED_SORT_BOOST_THRESHOLD " << best_sort_thresh << "\n";
    std::cout << "#define TUNED_SORT_TBB_THRESHOLD " << best_tbb_thresh << "\n";
    std::cout << "#define TUNED_QN_EXACT_THRESHOLD 64\n\n";
    std::cout << "#endif // ROBSCALE_QNSN_TUNED_THRESHOLDS_H\n";

    return 0;
}
