// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// adm_impl
double adm_impl(Rcpp::NumericVector x, double center, double constant);
RcppExport SEXP _robscale_adm_impl(SEXP xSEXP, SEXP centerSEXP, SEXP constantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type center(centerSEXP);
    Rcpp::traits::input_parameter< double >::type constant(constantSEXP);
    rcpp_result_gen = Rcpp::wrap(adm_impl(x, center, constant));
    return rcpp_result_gen;
END_RCPP
}
// adm_impl_auto
double adm_impl_auto(Rcpp::NumericVector x, double constant);
RcppExport SEXP _robscale_adm_impl_auto(SEXP xSEXP, SEXP constantSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type constant(constantSEXP);
    rcpp_result_gen = Rcpp::wrap(adm_impl_auto(x, constant));
    return rcpp_result_gen;
END_RCPP
}
// rob_loc_impl
double rob_loc_impl(Rcpp::NumericVector x, bool has_scale, double scale_val, int maxit, double tol);
RcppExport SEXP _robscale_rob_loc_impl(SEXP xSEXP, SEXP has_scaleSEXP, SEXP scale_valSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type has_scale(has_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type scale_val(scale_valSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rob_loc_impl(x, has_scale, scale_val, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// rob_scale_impl
double rob_scale_impl(Rcpp::NumericVector x, bool has_loc, double loc_val, double implbound, int maxit, double tol, int fallback);
RcppExport SEXP _robscale_rob_scale_impl(SEXP xSEXP, SEXP has_locSEXP, SEXP loc_valSEXP, SEXP implboundSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP fallbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type has_loc(has_locSEXP);
    Rcpp::traits::input_parameter< double >::type loc_val(loc_valSEXP);
    Rcpp::traits::input_parameter< double >::type implbound(implboundSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type fallback(fallbackSEXP);
    rcpp_result_gen = Rcpp::wrap(rob_scale_impl(x, has_loc, loc_val, implbound, maxit, tol, fallback));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_robscale_adm_impl", (DL_FUNC) &_robscale_adm_impl, 3},
    {"_robscale_adm_impl_auto", (DL_FUNC) &_robscale_adm_impl_auto, 2},
    {"_robscale_rob_loc_impl", (DL_FUNC) &_robscale_rob_loc_impl, 5},
    {"_robscale_rob_scale_impl", (DL_FUNC) &_robscale_rob_scale_impl, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_robscale(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
