#ifndef ROBSCALE_SORT_NET_H
#define ROBSCALE_SORT_NET_H

#include <algorithm>

namespace robscale {

#define SWAP_IF_GREATER(a, b) \
  do {                        \
    auto min_val = (std::min)((a), (b)); \
    auto max_val = (std::max)((a), (b)); \
    (a) = min_val;            \
    (b) = max_val;            \
  } while (0)

// Optimal sorting networks for small n.
// References: Knuth TAOCP Vol 3, optimal networks from sorting-network.org

template <typename T>
inline void sort_net_2(T* x) {
  SWAP_IF_GREATER(x[0], x[1]);
}

template <typename T>
inline void sort_net_3(T* x) {
  SWAP_IF_GREATER(x[0], x[1]);
  SWAP_IF_GREATER(x[0], x[2]);
  SWAP_IF_GREATER(x[1], x[2]);
}

template <typename T>
inline void sort_net_4(T* x) {
  SWAP_IF_GREATER(x[0], x[1]);
  SWAP_IF_GREATER(x[2], x[3]);
  SWAP_IF_GREATER(x[0], x[2]);
  SWAP_IF_GREATER(x[1], x[3]);
  SWAP_IF_GREATER(x[1], x[2]);
}

template <typename T>
inline void sort_net_5(T* x) {
  SWAP_IF_GREATER(x[0], x[1]);
  SWAP_IF_GREATER(x[2], x[3]);
  SWAP_IF_GREATER(x[0], x[2]);
  SWAP_IF_GREATER(x[1], x[3]);
  SWAP_IF_GREATER(x[1], x[2]);
  SWAP_IF_GREATER(x[0], x[4]);
  SWAP_IF_GREATER(x[2], x[4]);
  SWAP_IF_GREATER(x[1], x[2]);
  SWAP_IF_GREATER(x[3], x[4]);
}

// 12-comparator optimal network for n=6 (verified: Knuth TAOCP 5.3.4)
template <typename T>
inline void sort_net_6(T* x) {
  SWAP_IF_GREATER(x[0], x[5]);
  SWAP_IF_GREATER(x[1], x[3]);
  SWAP_IF_GREATER(x[2], x[4]);
  SWAP_IF_GREATER(x[1], x[2]);
  SWAP_IF_GREATER(x[3], x[4]);
  SWAP_IF_GREATER(x[0], x[3]);
  SWAP_IF_GREATER(x[2], x[5]);
  SWAP_IF_GREATER(x[0], x[1]);
  SWAP_IF_GREATER(x[2], x[3]);
  SWAP_IF_GREATER(x[4], x[5]);
  SWAP_IF_GREATER(x[1], x[2]);
  SWAP_IF_GREATER(x[3], x[4]);
}

// 16-comparator optimal network for n=7
// Source: Bert Dobbelaere's verified optimal sorting networks
template <typename T>
inline void sort_net_7(T* x) {
  SWAP_IF_GREATER(x[0], x[6]);
  SWAP_IF_GREATER(x[2], x[3]);
  SWAP_IF_GREATER(x[4], x[5]);
  SWAP_IF_GREATER(x[0], x[2]);
  SWAP_IF_GREATER(x[1], x[4]);
  SWAP_IF_GREATER(x[3], x[6]);
  SWAP_IF_GREATER(x[0], x[1]);
  SWAP_IF_GREATER(x[2], x[5]);
  SWAP_IF_GREATER(x[3], x[4]);
  SWAP_IF_GREATER(x[1], x[2]);
  SWAP_IF_GREATER(x[4], x[6]);
  SWAP_IF_GREATER(x[2], x[3]);
  SWAP_IF_GREATER(x[4], x[5]);
  SWAP_IF_GREATER(x[1], x[2]);
  SWAP_IF_GREATER(x[3], x[4]);
  SWAP_IF_GREATER(x[5], x[6]);
}

// 19-comparator optimal network for n=8
template <typename T>
inline void sort_net_8(T* x) {
  SWAP_IF_GREATER(x[0], x[1]);
  SWAP_IF_GREATER(x[2], x[3]);
  SWAP_IF_GREATER(x[4], x[5]);
  SWAP_IF_GREATER(x[6], x[7]);
  SWAP_IF_GREATER(x[0], x[2]);
  SWAP_IF_GREATER(x[1], x[3]);
  SWAP_IF_GREATER(x[4], x[6]);
  SWAP_IF_GREATER(x[5], x[7]);
  SWAP_IF_GREATER(x[1], x[2]);
  SWAP_IF_GREATER(x[5], x[6]);
  SWAP_IF_GREATER(x[0], x[4]);
  SWAP_IF_GREATER(x[1], x[5]);
  SWAP_IF_GREATER(x[2], x[6]);
  SWAP_IF_GREATER(x[3], x[7]);
  SWAP_IF_GREATER(x[2], x[4]);
  SWAP_IF_GREATER(x[3], x[5]);
  SWAP_IF_GREATER(x[1], x[2]);
  SWAP_IF_GREATER(x[3], x[4]);
  SWAP_IF_GREATER(x[5], x[6]);
}

// Sorting networks for n=9..16
// Source: Bert Dobbelaere's verified optimal sorting networks
// https://bertdobbelaere.github.io/sorting_networks.html

template <typename T>
inline void sort_net_9(T* x) { // 25 comparators
  SWAP_IF_GREATER(x[0],x[3]); SWAP_IF_GREATER(x[1],x[7]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[4],x[8]);
  SWAP_IF_GREATER(x[0],x[7]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[8]); SWAP_IF_GREATER(x[5],x[6]);
  SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[7],x[8]);
  SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[5],x[7]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[8]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]);
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]);
}

template <typename T>
inline void sort_net_10(T* x) { // 29 comparators
  SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[7]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[6]);
  SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[7],x[9]);
  SWAP_IF_GREATER(x[0],x[3]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[6],x[9]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[8],x[9]);
  SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[6],x[7]);
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[7],x[8]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]);
}

template <typename T>
inline void sort_net_11(T* x) { // 35 comparators
  SWAP_IF_GREATER(x[0],x[9]); SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[5],x[8]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[8]);
  SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[4],x[7]); SWAP_IF_GREATER(x[8],x[10]);
  SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[6],x[8]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[9]);
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]);
}

template <typename T>
inline void sort_net_12(T* x) { // 39 comparators
  SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[1],x[7]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[5],x[9]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[9],x[11]);
  SWAP_IF_GREATER(x[0],x[3]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[11]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[7],x[10]);
  SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[8],x[10]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]);
  SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]);
}

template <typename T>
inline void sort_net_13(T* x) { // 45 comparators
  SWAP_IF_GREATER(x[0],x[12]); SWAP_IF_GREATER(x[1],x[10]); SWAP_IF_GREATER(x[2],x[9]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[5],x[11]); SWAP_IF_GREATER(x[6],x[8]);
  SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[11]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[8],x[10]);
  SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]);
  SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[8],x[11]); SWAP_IF_GREATER(x[10],x[12]);
  SWAP_IF_GREATER(x[0],x[5]); SWAP_IF_GREATER(x[3],x[8]); SWAP_IF_GREATER(x[4],x[7]); SWAP_IF_GREATER(x[6],x[11]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[6],x[8]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]);
}

template <typename T>
inline void sort_net_14(T* x) { // 51 comparators
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]);
  SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[13]);
  SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[11],x[12]);
  SWAP_IF_GREATER(x[0],x[6]); SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[3],x[9]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[7],x[13]); SWAP_IF_GREATER(x[8],x[12]);
  SWAP_IF_GREATER(x[2],x[10]); SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[7],x[9]);
  SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[2],x[8]); SWAP_IF_GREATER(x[5],x[11]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[10],x[12]);
  SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[12]);
  SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[11]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[6],x[7]);
}

template <typename T>
inline void sort_net_15(T* x) { // 56 comparators
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[10]); SWAP_IF_GREATER(x[4],x[14]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[6],x[13]); SWAP_IF_GREATER(x[7],x[12]); SWAP_IF_GREATER(x[9],x[11]);
  SWAP_IF_GREATER(x[0],x[14]); SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[8]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[13]);
  SWAP_IF_GREATER(x[0],x[7]); SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[2],x[9]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[5],x[11]); SWAP_IF_GREATER(x[8],x[13]); SWAP_IF_GREATER(x[12],x[14]);
  SWAP_IF_GREATER(x[0],x[6]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[0],x[3]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[4],x[7]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[13]);
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[11],x[12]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]);
}

template <typename T>
inline void sort_net_16(T* x) { // 60 comparators
  SWAP_IF_GREATER(x[0],x[13]); SWAP_IF_GREATER(x[1],x[12]); SWAP_IF_GREATER(x[2],x[15]); SWAP_IF_GREATER(x[3],x[14]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[0],x[5]); SWAP_IF_GREATER(x[1],x[7]); SWAP_IF_GREATER(x[2],x[9]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[6],x[13]); SWAP_IF_GREATER(x[8],x[14]); SWAP_IF_GREATER(x[10],x[15]); SWAP_IF_GREATER(x[11],x[12]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]);
  SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[5],x[11]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[15]);
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[12]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[11],x[14]);
  SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[11],x[13]);
  SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[10],x[12]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]);
  SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]);
}

template <typename T>
inline void sort_net_17(T* x) { // 71 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[11]); SWAP_IF_GREATER(x[1],x[15]); SWAP_IF_GREATER(x[2],x[10]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[8],x[12]);
  SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[0],x[6]); SWAP_IF_GREATER(x[1],x[13]); SWAP_IF_GREATER(x[2],x[8]); SWAP_IF_GREATER(x[4],x[14]);
  SWAP_IF_GREATER(x[5],x[15]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[4],x[9]); SWAP_IF_GREATER(x[6],x[16]);
  SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[13]);
  SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[0],x[3]); SWAP_IF_GREATER(x[2],x[5]);
  SWAP_IF_GREATER(x[6],x[11]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[12],x[15]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[0],x[1]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[6],x[12]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[14],x[15]);
  SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[2],x[7]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[6],x[8]);
  SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]);
  SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]);
}

template <typename T>
inline void sort_net_18(T* x) { // 77 comparators (Dobbelaere)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[12]);
  SWAP_IF_GREATER(x[5],x[13]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[0],x[14]);
  SWAP_IF_GREATER(x[1],x[16]); SWAP_IF_GREATER(x[2],x[15]); SWAP_IF_GREATER(x[3],x[17]); SWAP_IF_GREATER(x[0],x[6]); SWAP_IF_GREATER(x[1],x[10]); SWAP_IF_GREATER(x[2],x[9]);
  SWAP_IF_GREATER(x[7],x[16]); SWAP_IF_GREATER(x[8],x[15]); SWAP_IF_GREATER(x[11],x[17]); SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[3],x[9]); SWAP_IF_GREATER(x[5],x[7]);
  SWAP_IF_GREATER(x[8],x[14]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[3],x[13]);
  SWAP_IF_GREATER(x[4],x[14]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[12],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[1],x[2]);
  SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[4],x[8]);
  SWAP_IF_GREATER(x[5],x[12]); SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[2],x[8]);
  SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[9],x[15]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[13],x[16]);
  SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[13],x[15]);
  SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[3],x[4]);
  SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]);
}

template <typename T>
inline void sort_net_19(T* x) { // 85 comparators (Dobbelaere)
  SWAP_IF_GREATER(x[0],x[12]); SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[2],x[8]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[17]); SWAP_IF_GREATER(x[7],x[11]);
  SWAP_IF_GREATER(x[9],x[14]); SWAP_IF_GREATER(x[10],x[13]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[7]); SWAP_IF_GREATER(x[3],x[6]);
  SWAP_IF_GREATER(x[4],x[11]); SWAP_IF_GREATER(x[5],x[17]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[10],x[15]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[14],x[18]);
  SWAP_IF_GREATER(x[3],x[10]); SWAP_IF_GREATER(x[4],x[14]); SWAP_IF_GREATER(x[5],x[15]); SWAP_IF_GREATER(x[6],x[13]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[11],x[17]);
  SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[0],x[7]); SWAP_IF_GREATER(x[1],x[10]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[9],x[15]); SWAP_IF_GREATER(x[11],x[16]);
  SWAP_IF_GREATER(x[12],x[17]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[0],x[3]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[11]);
  SWAP_IF_GREATER(x[12],x[16]); SWAP_IF_GREATER(x[1],x[8]); SWAP_IF_GREATER(x[2],x[9]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[6],x[15]); SWAP_IF_GREATER(x[7],x[13]);
  SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[18]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[12]);
  SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[8]);
  SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[5],x[8]);
  SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[10],x[13]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[3],x[6]);
  SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[12],x[14]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]);
  SWAP_IF_GREATER(x[14],x[15]);
}

template <typename T>
inline void sort_net_20(T* x) { // 91 comparators (Dobbelaere)
  SWAP_IF_GREATER(x[0],x[3]); SWAP_IF_GREATER(x[1],x[7]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[10],x[13]);
  SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[12],x[18]); SWAP_IF_GREATER(x[14],x[17]); SWAP_IF_GREATER(x[16],x[19]); SWAP_IF_GREATER(x[0],x[14]); SWAP_IF_GREATER(x[1],x[11]);
  SWAP_IF_GREATER(x[2],x[16]); SWAP_IF_GREATER(x[3],x[17]); SWAP_IF_GREATER(x[4],x[12]); SWAP_IF_GREATER(x[5],x[19]); SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[7],x[15]);
  SWAP_IF_GREATER(x[8],x[18]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[8]); SWAP_IF_GREATER(x[5],x[7]);
  SWAP_IF_GREATER(x[11],x[16]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[15],x[19]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[2],x[12]);
  SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[11]); SWAP_IF_GREATER(x[7],x[17]); SWAP_IF_GREATER(x[8],x[15]); SWAP_IF_GREATER(x[13],x[18]); SWAP_IF_GREATER(x[14],x[16]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[18],x[19]);
  SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[13],x[18]);
  SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[15]); SWAP_IF_GREATER(x[14],x[16]);
  SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[12],x[14]);
  SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]);
  SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[6]);
  SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[16],x[17]);
  SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[14],x[15]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[15],x[16]);
}

template <typename T>
inline void sort_net_21(T* x) { // 99 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]);
  SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[15]);
  SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[10]); SWAP_IF_GREATER(x[3],x[11]);
  SWAP_IF_GREATER(x[4],x[12]); SWAP_IF_GREATER(x[5],x[13]); SWAP_IF_GREATER(x[6],x[14]); SWAP_IF_GREATER(x[7],x[15]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[5]);
  SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[6],x[20]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[15],x[19]);
  SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[18]); SWAP_IF_GREATER(x[7],x[20]); SWAP_IF_GREATER(x[2],x[16]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[5],x[18]);
  SWAP_IF_GREATER(x[7],x[17]); SWAP_IF_GREATER(x[11],x[20]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[3],x[8]); SWAP_IF_GREATER(x[6],x[12]); SWAP_IF_GREATER(x[7],x[10]);
  SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[14],x[18]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[1],x[7]);
  SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[9]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[17],x[19]);
  SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[6],x[13]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[12],x[16]);
  SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[10],x[12]);
  SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[9]);
  SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]);
  SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[3],x[4]);
  SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]);
  SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]);
}

template <typename T>
inline void sort_net_22(T* x) { // 106 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[0],x[2]);
  SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[14],x[16]);
  SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[6]);
  SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[14],x[18]); SWAP_IF_GREATER(x[15],x[19]);
  SWAP_IF_GREATER(x[16],x[20]); SWAP_IF_GREATER(x[17],x[21]); SWAP_IF_GREATER(x[0],x[14]); SWAP_IF_GREATER(x[1],x[15]); SWAP_IF_GREATER(x[2],x[18]); SWAP_IF_GREATER(x[3],x[19]);
  SWAP_IF_GREATER(x[4],x[16]); SWAP_IF_GREATER(x[5],x[17]); SWAP_IF_GREATER(x[6],x[20]); SWAP_IF_GREATER(x[7],x[21]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[10],x[12]);
  SWAP_IF_GREATER(x[2],x[8]); SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[10],x[18]); SWAP_IF_GREATER(x[12],x[15]); SWAP_IF_GREATER(x[13],x[19]);
  SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[10]); SWAP_IF_GREATER(x[3],x[16]); SWAP_IF_GREATER(x[5],x[18]); SWAP_IF_GREATER(x[6],x[14]); SWAP_IF_GREATER(x[7],x[15]);
  SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[11],x[20]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[10]);
  SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[5],x[12]); SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[11],x[18]); SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[15],x[19]);
  SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[7],x[13]); SWAP_IF_GREATER(x[8],x[14]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[17],x[20]); SWAP_IF_GREATER(x[1],x[2]);
  SWAP_IF_GREATER(x[3],x[8]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[13],x[18]); SWAP_IF_GREATER(x[15],x[17]);
  SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[11],x[16]); SWAP_IF_GREATER(x[12],x[14]);
  SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[11],x[13]);
  SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]);
}

template <typename T>
inline void sort_net_23(T* x) { // 114 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[0],x[2]);
  SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]);
  SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[5]);
  SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[11],x[15]);
  SWAP_IF_GREATER(x[17],x[21]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[19],x[22]); SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[10]);
  SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[4],x[12]); SWAP_IF_GREATER(x[5],x[13]); SWAP_IF_GREATER(x[6],x[14]); SWAP_IF_GREATER(x[7],x[15]); SWAP_IF_GREATER(x[1],x[2]);
  SWAP_IF_GREATER(x[5],x[18]); SWAP_IF_GREATER(x[7],x[19]); SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[10],x[21]); SWAP_IF_GREATER(x[12],x[20]); SWAP_IF_GREATER(x[15],x[22]);
  SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[10],x[18]); SWAP_IF_GREATER(x[11],x[21]); SWAP_IF_GREATER(x[12],x[17]); SWAP_IF_GREATER(x[13],x[20]);
  SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[3],x[17]); SWAP_IF_GREATER(x[6],x[16]); SWAP_IF_GREATER(x[7],x[14]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[15],x[19]);
  SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[13],x[16]);
  SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[0],x[5]); SWAP_IF_GREATER(x[1],x[8]); SWAP_IF_GREATER(x[2],x[12]);
  SWAP_IF_GREATER(x[3],x[9]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[7],x[13]); SWAP_IF_GREATER(x[11],x[17]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[18],x[20]);
  SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[13],x[18]);
  SWAP_IF_GREATER(x[14],x[17]); SWAP_IF_GREATER(x[15],x[20]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[10]);
  SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[2],x[3]);
  SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[19]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]);
  SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[16],x[17]);
}

template <typename T>
inline void sort_net_24(T* x) { // 120 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[20]); SWAP_IF_GREATER(x[1],x[12]); SWAP_IF_GREATER(x[2],x[16]); SWAP_IF_GREATER(x[3],x[23]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[10]);
  SWAP_IF_GREATER(x[7],x[21]); SWAP_IF_GREATER(x[8],x[14]); SWAP_IF_GREATER(x[9],x[15]); SWAP_IF_GREATER(x[11],x[22]); SWAP_IF_GREATER(x[13],x[18]); SWAP_IF_GREATER(x[17],x[19]);
  SWAP_IF_GREATER(x[0],x[3]); SWAP_IF_GREATER(x[1],x[11]); SWAP_IF_GREATER(x[2],x[7]); SWAP_IF_GREATER(x[4],x[17]); SWAP_IF_GREATER(x[5],x[13]); SWAP_IF_GREATER(x[6],x[19]);
  SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[18]); SWAP_IF_GREATER(x[12],x[22]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[21]); SWAP_IF_GREATER(x[20],x[23]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[12]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[10]);
  SWAP_IF_GREATER(x[11],x[20]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[14],x[17]); SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[22],x[23]);
  SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[6],x[11]); SWAP_IF_GREATER(x[7],x[14]); SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[12],x[17]);
  SWAP_IF_GREATER(x[15],x[19]); SWAP_IF_GREATER(x[18],x[21]); SWAP_IF_GREATER(x[1],x[8]); SWAP_IF_GREATER(x[3],x[14]); SWAP_IF_GREATER(x[4],x[7]); SWAP_IF_GREATER(x[9],x[20]);
  SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[15],x[22]); SWAP_IF_GREATER(x[16],x[19]); SWAP_IF_GREATER(x[0],x[7]); SWAP_IF_GREATER(x[1],x[5]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[6],x[11]); SWAP_IF_GREATER(x[8],x[15]); SWAP_IF_GREATER(x[9],x[14]); SWAP_IF_GREATER(x[10],x[13]); SWAP_IF_GREATER(x[12],x[17]);
  SWAP_IF_GREATER(x[16],x[23]); SWAP_IF_GREATER(x[18],x[22]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[4],x[7]);
  SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[14],x[18]); SWAP_IF_GREATER(x[16],x[19]); SWAP_IF_GREATER(x[17],x[22]);
  SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[1],x[2]);
  SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[19]);
  SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[20]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[6],x[7]);
  SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[13],x[18]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[3],x[4]);
  SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[4],x[6]);
  SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[5],x[6]);
  SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]);
}

template <typename T>
inline void sort_net_25(T* x) { // 130 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[23]);
  SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]);
  SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[23],x[24]);
  SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]);
  SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[18],x[21]); SWAP_IF_GREATER(x[20],x[23]); SWAP_IF_GREATER(x[22],x[24]); SWAP_IF_GREATER(x[0],x[8]);
  SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[10]); SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[4],x[12]); SWAP_IF_GREATER(x[5],x[13]); SWAP_IF_GREATER(x[6],x[14]);
  SWAP_IF_GREATER(x[7],x[15]); SWAP_IF_GREATER(x[16],x[20]); SWAP_IF_GREATER(x[17],x[22]); SWAP_IF_GREATER(x[19],x[24]); SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[1],x[18]);
  SWAP_IF_GREATER(x[3],x[21]); SWAP_IF_GREATER(x[5],x[23]); SWAP_IF_GREATER(x[6],x[19]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[15],x[24]); SWAP_IF_GREATER(x[1],x[16]);
  SWAP_IF_GREATER(x[3],x[17]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[13],x[19]); SWAP_IF_GREATER(x[14],x[23]); SWAP_IF_GREATER(x[0],x[1]);
  SWAP_IF_GREATER(x[2],x[16]); SWAP_IF_GREATER(x[3],x[8]); SWAP_IF_GREATER(x[7],x[20]); SWAP_IF_GREATER(x[10],x[13]); SWAP_IF_GREATER(x[11],x[22]); SWAP_IF_GREATER(x[15],x[23]);
  SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[7],x[18]); SWAP_IF_GREATER(x[11],x[21]); SWAP_IF_GREATER(x[15],x[20]); SWAP_IF_GREATER(x[19],x[22]);
  SWAP_IF_GREATER(x[4],x[7]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[9],x[18]); SWAP_IF_GREATER(x[10],x[17]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[21]);
  SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[22],x[23]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]);
  SWAP_IF_GREATER(x[11],x[16]); SWAP_IF_GREATER(x[12],x[17]); SWAP_IF_GREATER(x[13],x[18]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[20],x[22]); SWAP_IF_GREATER(x[1],x[3]);
  SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[5],x[11]); SWAP_IF_GREATER(x[6],x[16]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[12],x[13]);
  SWAP_IF_GREATER(x[14],x[19]); SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[8],x[11]);
  SWAP_IF_GREATER(x[10],x[16]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[7],x[8]);
  SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[4],x[7]);
  SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[17],x[19]);
  SWAP_IF_GREATER(x[18],x[21]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]);
  SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]);
}

template <typename T>
inline void sort_net_26(T* x) { // 138 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[23]);
  SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]);
  SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[22],x[24]);
  SWAP_IF_GREATER(x[23],x[25]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[8],x[14]);
  SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[10],x[15]); SWAP_IF_GREATER(x[11],x[17]); SWAP_IF_GREATER(x[18],x[22]); SWAP_IF_GREATER(x[19],x[24]); SWAP_IF_GREATER(x[20],x[23]);
  SWAP_IF_GREATER(x[21],x[25]); SWAP_IF_GREATER(x[0],x[18]); SWAP_IF_GREATER(x[1],x[19]); SWAP_IF_GREATER(x[2],x[20]); SWAP_IF_GREATER(x[3],x[21]); SWAP_IF_GREATER(x[4],x[22]);
  SWAP_IF_GREATER(x[5],x[23]); SWAP_IF_GREATER(x[6],x[24]); SWAP_IF_GREATER(x[7],x[25]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[3],x[11]);
  SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[13]); SWAP_IF_GREATER(x[12],x[15]); SWAP_IF_GREATER(x[14],x[22]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[0],x[8]);
  SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[14]); SWAP_IF_GREATER(x[6],x[12]); SWAP_IF_GREATER(x[7],x[15]); SWAP_IF_GREATER(x[10],x[18]); SWAP_IF_GREATER(x[11],x[23]);
  SWAP_IF_GREATER(x[13],x[19]); SWAP_IF_GREATER(x[16],x[24]); SWAP_IF_GREATER(x[17],x[25]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[18]); SWAP_IF_GREATER(x[4],x[8]);
  SWAP_IF_GREATER(x[7],x[22]); SWAP_IF_GREATER(x[17],x[21]); SWAP_IF_GREATER(x[23],x[24]); SWAP_IF_GREATER(x[3],x[14]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[5],x[18]);
  SWAP_IF_GREATER(x[7],x[20]); SWAP_IF_GREATER(x[8],x[13]); SWAP_IF_GREATER(x[11],x[22]); SWAP_IF_GREATER(x[12],x[17]); SWAP_IF_GREATER(x[15],x[21]); SWAP_IF_GREATER(x[1],x[4]);
  SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[19],x[20]);
  SWAP_IF_GREATER(x[21],x[24]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[3],x[10]); SWAP_IF_GREATER(x[6],x[14]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[11],x[19]);
  SWAP_IF_GREATER(x[12],x[16]); SWAP_IF_GREATER(x[15],x[22]); SWAP_IF_GREATER(x[20],x[23]); SWAP_IF_GREATER(x[2],x[8]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[6],x[9]);
  SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[16],x[19]); SWAP_IF_GREATER(x[17],x[23]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[2],x[4]);
  SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[11]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[19]);
  SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[20],x[22]); SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[6],x[7]);
  SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[17],x[20]); SWAP_IF_GREATER(x[18],x[19]);
  SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]);
  SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]);
}

template <typename T>
inline void sort_net_27(T* x) { // 147 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[23],x[24]);
  SWAP_IF_GREATER(x[25],x[26]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]);
  SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[20],x[22]);
  SWAP_IF_GREATER(x[23],x[25]); SWAP_IF_GREATER(x[24],x[26]); SWAP_IF_GREATER(x[0],x[23]); SWAP_IF_GREATER(x[1],x[24]); SWAP_IF_GREATER(x[2],x[25]); SWAP_IF_GREATER(x[3],x[26]);
  SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[19]);
  SWAP_IF_GREATER(x[16],x[20]); SWAP_IF_GREATER(x[17],x[21]); SWAP_IF_GREATER(x[18],x[22]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[2],x[19]);
  SWAP_IF_GREATER(x[3],x[20]); SWAP_IF_GREATER(x[5],x[13]); SWAP_IF_GREATER(x[9],x[21]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[12],x[16]); SWAP_IF_GREATER(x[17],x[23]);
  SWAP_IF_GREATER(x[18],x[24]); SWAP_IF_GREATER(x[22],x[26]); SWAP_IF_GREATER(x[5],x[17]); SWAP_IF_GREATER(x[6],x[16]); SWAP_IF_GREATER(x[7],x[22]); SWAP_IF_GREATER(x[9],x[25]);
  SWAP_IF_GREATER(x[10],x[24]); SWAP_IF_GREATER(x[12],x[15]); SWAP_IF_GREATER(x[13],x[20]); SWAP_IF_GREATER(x[14],x[26]); SWAP_IF_GREATER(x[1],x[12]); SWAP_IF_GREATER(x[4],x[15]);
  SWAP_IF_GREATER(x[7],x[23]); SWAP_IF_GREATER(x[10],x[19]); SWAP_IF_GREATER(x[11],x[16]); SWAP_IF_GREATER(x[13],x[18]); SWAP_IF_GREATER(x[20],x[24]); SWAP_IF_GREATER(x[22],x[25]);
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[6],x[12]); SWAP_IF_GREATER(x[8],x[11]); SWAP_IF_GREATER(x[9],x[15]); SWAP_IF_GREATER(x[10],x[17]); SWAP_IF_GREATER(x[14],x[24]);
  SWAP_IF_GREATER(x[16],x[21]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[2],x[8]); SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[12],x[15]);
  SWAP_IF_GREATER(x[14],x[20]); SWAP_IF_GREATER(x[16],x[22]); SWAP_IF_GREATER(x[21],x[25]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[3],x[17]); SWAP_IF_GREATER(x[8],x[13]);
  SWAP_IF_GREATER(x[11],x[23]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[10]); SWAP_IF_GREATER(x[5],x[6]);
  SWAP_IF_GREATER(x[7],x[13]); SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[14],x[21]); SWAP_IF_GREATER(x[18],x[23]); SWAP_IF_GREATER(x[20],x[22]); SWAP_IF_GREATER(x[4],x[5]);
  SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[19],x[23]); SWAP_IF_GREATER(x[22],x[24]);
  SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[13]);
  SWAP_IF_GREATER(x[14],x[18]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[16],x[19]); SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[8]);
  SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[17],x[19]);
  SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[23]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[8],x[11]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[12],x[14]);
  SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]);
  SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[21],x[22]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[20]);
}

template <typename T>
inline void sort_net_28(T* x) { // 155 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[23]);
  SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[26],x[27]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]);
  SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[17],x[19]);
  SWAP_IF_GREATER(x[20],x[22]); SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[24],x[26]); SWAP_IF_GREATER(x[25],x[27]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[5]);
  SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[14],x[18]); SWAP_IF_GREATER(x[15],x[19]);
  SWAP_IF_GREATER(x[20],x[24]); SWAP_IF_GREATER(x[21],x[25]); SWAP_IF_GREATER(x[22],x[26]); SWAP_IF_GREATER(x[23],x[27]); SWAP_IF_GREATER(x[0],x[20]); SWAP_IF_GREATER(x[1],x[21]);
  SWAP_IF_GREATER(x[2],x[22]); SWAP_IF_GREATER(x[3],x[23]); SWAP_IF_GREATER(x[4],x[24]); SWAP_IF_GREATER(x[5],x[25]); SWAP_IF_GREATER(x[6],x[26]); SWAP_IF_GREATER(x[7],x[27]);
  SWAP_IF_GREATER(x[9],x[17]); SWAP_IF_GREATER(x[10],x[18]); SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[12],x[16]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[4],x[20]);
  SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[23]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[11],x[18]);
  SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[15],x[19]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[25],x[26]); SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[1],x[9]);
  SWAP_IF_GREATER(x[2],x[12]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[10]); SWAP_IF_GREATER(x[6],x[16]); SWAP_IF_GREATER(x[7],x[13]); SWAP_IF_GREATER(x[11],x[21]);
  SWAP_IF_GREATER(x[14],x[20]); SWAP_IF_GREATER(x[15],x[25]); SWAP_IF_GREATER(x[17],x[23]); SWAP_IF_GREATER(x[18],x[26]); SWAP_IF_GREATER(x[19],x[27]); SWAP_IF_GREATER(x[22],x[24]);
  SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[5],x[17]); SWAP_IF_GREATER(x[8],x[14]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[10],x[22]);
  SWAP_IF_GREATER(x[13],x[19]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[20],x[24]); SWAP_IF_GREATER(x[23],x[25]); SWAP_IF_GREATER(x[1],x[8]); SWAP_IF_GREATER(x[3],x[9]);
  SWAP_IF_GREATER(x[5],x[11]); SWAP_IF_GREATER(x[6],x[10]); SWAP_IF_GREATER(x[7],x[15]); SWAP_IF_GREATER(x[12],x[20]); SWAP_IF_GREATER(x[16],x[22]); SWAP_IF_GREATER(x[17],x[21]);
  SWAP_IF_GREATER(x[18],x[24]); SWAP_IF_GREATER(x[19],x[26]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[10],x[16]);
  SWAP_IF_GREATER(x[11],x[17]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[18],x[22]); SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[25],x[26]);
  SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[6],x[12]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[15],x[21]);
  SWAP_IF_GREATER(x[16],x[20]); SWAP_IF_GREATER(x[19],x[23]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[6],x[8]); SWAP_IF_GREATER(x[7],x[16]); SWAP_IF_GREATER(x[9],x[14]);
  SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[20]); SWAP_IF_GREATER(x[13],x[18]); SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[23],x[25]);
  SWAP_IF_GREATER(x[3],x[10]); SWAP_IF_GREATER(x[5],x[12]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[15],x[22]);
  SWAP_IF_GREATER(x[17],x[24]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[12]);
  SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[17],x[20]); SWAP_IF_GREATER(x[19],x[22]); SWAP_IF_GREATER(x[21],x[24]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[23],x[24]);
}

template <typename T>
inline void sort_net_29(T* x) { // 164 comparators (Dobbelaere optimal)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[28]); SWAP_IF_GREATER(x[17],x[26]); SWAP_IF_GREATER(x[18],x[25]); SWAP_IF_GREATER(x[19],x[23]);
  SWAP_IF_GREATER(x[21],x[27]); SWAP_IF_GREATER(x[22],x[24]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]);
  SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[17],x[22]); SWAP_IF_GREATER(x[18],x[19]);
  SWAP_IF_GREATER(x[20],x[27]); SWAP_IF_GREATER(x[23],x[25]); SWAP_IF_GREATER(x[24],x[26]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[6]);
  SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[16],x[20]);
  SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[22]); SWAP_IF_GREATER(x[23],x[24]); SWAP_IF_GREATER(x[25],x[26]); SWAP_IF_GREATER(x[27],x[28]); SWAP_IF_GREATER(x[0],x[8]);
  SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[10]); SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[4],x[12]); SWAP_IF_GREATER(x[5],x[13]); SWAP_IF_GREATER(x[6],x[14]);
  SWAP_IF_GREATER(x[7],x[15]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[20],x[22]); SWAP_IF_GREATER(x[21],x[25]); SWAP_IF_GREATER(x[24],x[27]); SWAP_IF_GREATER(x[26],x[28]);
  SWAP_IF_GREATER(x[1],x[8]); SWAP_IF_GREATER(x[2],x[24]); SWAP_IF_GREATER(x[4],x[19]); SWAP_IF_GREATER(x[5],x[20]); SWAP_IF_GREATER(x[6],x[21]); SWAP_IF_GREATER(x[7],x[27]);
  SWAP_IF_GREATER(x[9],x[18]); SWAP_IF_GREATER(x[10],x[23]); SWAP_IF_GREATER(x[11],x[26]); SWAP_IF_GREATER(x[13],x[22]); SWAP_IF_GREATER(x[14],x[25]); SWAP_IF_GREATER(x[15],x[28]);
  SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[0],x[6]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[24]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[12],x[19]);
  SWAP_IF_GREATER(x[13],x[18]); SWAP_IF_GREATER(x[14],x[21]); SWAP_IF_GREATER(x[15],x[25]); SWAP_IF_GREATER(x[20],x[23]); SWAP_IF_GREATER(x[26],x[27]); SWAP_IF_GREATER(x[0],x[16]);
  SWAP_IF_GREATER(x[1],x[6]); SWAP_IF_GREATER(x[3],x[12]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[5],x[17]); SWAP_IF_GREATER(x[7],x[24]); SWAP_IF_GREATER(x[14],x[20]);
  SWAP_IF_GREATER(x[15],x[26]); SWAP_IF_GREATER(x[18],x[21]); SWAP_IF_GREATER(x[19],x[23]); SWAP_IF_GREATER(x[25],x[27]); SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[16]);
  SWAP_IF_GREATER(x[3],x[10]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[18]); SWAP_IF_GREATER(x[8],x[17]); SWAP_IF_GREATER(x[11],x[19]); SWAP_IF_GREATER(x[13],x[14]);
  SWAP_IF_GREATER(x[15],x[22]); SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[25],x[26]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[8]);
  SWAP_IF_GREATER(x[6],x[16]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[9],x[17]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[14],x[20]); SWAP_IF_GREATER(x[15],x[18]);
  SWAP_IF_GREATER(x[19],x[24]); SWAP_IF_GREATER(x[22],x[27]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[10],x[13]); SWAP_IF_GREATER(x[11],x[19]);
  SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[26]); SWAP_IF_GREATER(x[23],x[24]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[6]);
  SWAP_IF_GREATER(x[7],x[16]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[11],x[17]); SWAP_IF_GREATER(x[15],x[19]); SWAP_IF_GREATER(x[18],x[23]); SWAP_IF_GREATER(x[24],x[25]);
  SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[12],x[16]); SWAP_IF_GREATER(x[14],x[17]);
  SWAP_IF_GREATER(x[15],x[20]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[22],x[24]); SWAP_IF_GREATER(x[5],x[8]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[9],x[12]);
  SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[20]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[21],x[23]);
  SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[15]);
  SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]);
  SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]);
  SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[23]);
}

template <typename T>
inline void sort_net_30(T* x) { // 172 comparators (Dobbelaere)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[23]);
  SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[26],x[27]); SWAP_IF_GREATER(x[28],x[29]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]);
  SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[18],x[20]);
  SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[22],x[24]); SWAP_IF_GREATER(x[23],x[25]); SWAP_IF_GREATER(x[26],x[28]); SWAP_IF_GREATER(x[27],x[29]); SWAP_IF_GREATER(x[0],x[4]);
  SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[8],x[14]); SWAP_IF_GREATER(x[9],x[17]); SWAP_IF_GREATER(x[10],x[16]);
  SWAP_IF_GREATER(x[12],x[20]); SWAP_IF_GREATER(x[13],x[19]); SWAP_IF_GREATER(x[15],x[21]); SWAP_IF_GREATER(x[22],x[26]); SWAP_IF_GREATER(x[23],x[27]); SWAP_IF_GREATER(x[24],x[28]);
  SWAP_IF_GREATER(x[25],x[29]); SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[14]); SWAP_IF_GREATER(x[3],x[17]); SWAP_IF_GREATER(x[4],x[10]);
  SWAP_IF_GREATER(x[5],x[11]); SWAP_IF_GREATER(x[6],x[16]); SWAP_IF_GREATER(x[12],x[26]); SWAP_IF_GREATER(x[13],x[23]); SWAP_IF_GREATER(x[15],x[27]); SWAP_IF_GREATER(x[18],x[24]);
  SWAP_IF_GREATER(x[19],x[25]); SWAP_IF_GREATER(x[20],x[28]); SWAP_IF_GREATER(x[21],x[29]); SWAP_IF_GREATER(x[1],x[13]); SWAP_IF_GREATER(x[2],x[12]); SWAP_IF_GREATER(x[3],x[15]);
  SWAP_IF_GREATER(x[4],x[18]); SWAP_IF_GREATER(x[5],x[19]); SWAP_IF_GREATER(x[6],x[20]); SWAP_IF_GREATER(x[7],x[21]); SWAP_IF_GREATER(x[8],x[22]); SWAP_IF_GREATER(x[9],x[23]);
  SWAP_IF_GREATER(x[10],x[24]); SWAP_IF_GREATER(x[11],x[25]); SWAP_IF_GREATER(x[14],x[26]); SWAP_IF_GREATER(x[16],x[28]); SWAP_IF_GREATER(x[17],x[27]); SWAP_IF_GREATER(x[0],x[4]);
  SWAP_IF_GREATER(x[2],x[8]); SWAP_IF_GREATER(x[3],x[13]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[6],x[22]); SWAP_IF_GREATER(x[7],x[23]); SWAP_IF_GREATER(x[10],x[12]);
  SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[14],x[18]); SWAP_IF_GREATER(x[16],x[26]); SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[20],x[24]); SWAP_IF_GREATER(x[21],x[27]);
  SWAP_IF_GREATER(x[25],x[29]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[14]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[9],x[13]);
  SWAP_IF_GREATER(x[11],x[17]); SWAP_IF_GREATER(x[12],x[18]); SWAP_IF_GREATER(x[15],x[28]); SWAP_IF_GREATER(x[16],x[20]); SWAP_IF_GREATER(x[21],x[25]); SWAP_IF_GREATER(x[24],x[26]);
  SWAP_IF_GREATER(x[27],x[29]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[5],x[9]); SWAP_IF_GREATER(x[6],x[14]); SWAP_IF_GREATER(x[7],x[13]); SWAP_IF_GREATER(x[8],x[10]);
  SWAP_IF_GREATER(x[15],x[23]); SWAP_IF_GREATER(x[16],x[22]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[20],x[24]); SWAP_IF_GREATER(x[25],x[27]); SWAP_IF_GREATER(x[6],x[8]);
  SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[12],x[16]); SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[15],x[19]); SWAP_IF_GREATER(x[18],x[22]);
  SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[12],x[14]);
  SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[20],x[22]); SWAP_IF_GREATER(x[23],x[25]); SWAP_IF_GREATER(x[1],x[8]);
  SWAP_IF_GREATER(x[3],x[18]); SWAP_IF_GREATER(x[5],x[20]); SWAP_IF_GREATER(x[7],x[22]); SWAP_IF_GREATER(x[9],x[24]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[26]);
  SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[21],x[28]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[10]);
  SWAP_IF_GREATER(x[5],x[12]); SWAP_IF_GREATER(x[7],x[14]); SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[11],x[18]); SWAP_IF_GREATER(x[13],x[20]); SWAP_IF_GREATER(x[15],x[22]);
  SWAP_IF_GREATER(x[17],x[24]); SWAP_IF_GREATER(x[19],x[26]); SWAP_IF_GREATER(x[27],x[28]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[6]); SWAP_IF_GREATER(x[5],x[8]);
  SWAP_IF_GREATER(x[7],x[10]); SWAP_IF_GREATER(x[9],x[12]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[17],x[20]);
  SWAP_IF_GREATER(x[19],x[22]); SWAP_IF_GREATER(x[21],x[24]); SWAP_IF_GREATER(x[23],x[26]); SWAP_IF_GREATER(x[25],x[27]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]);
  SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]);
  SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[23],x[24]); SWAP_IF_GREATER(x[25],x[26]);
}

template <typename T>
inline void sort_net_31(T* x) { // 180 comparators (Dobbelaere)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[23]);
  SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[26],x[27]); SWAP_IF_GREATER(x[28],x[29]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]); SWAP_IF_GREATER(x[4],x[6]);
  SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[15]); SWAP_IF_GREATER(x[16],x[18]);
  SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[20],x[22]); SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[24],x[26]); SWAP_IF_GREATER(x[25],x[27]); SWAP_IF_GREATER(x[28],x[30]);
  SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[7]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]);
  SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[16],x[20]); SWAP_IF_GREATER(x[17],x[21]); SWAP_IF_GREATER(x[18],x[22]); SWAP_IF_GREATER(x[19],x[23]);
  SWAP_IF_GREATER(x[24],x[28]); SWAP_IF_GREATER(x[25],x[29]); SWAP_IF_GREATER(x[26],x[30]); SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[10]);
  SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[4],x[12]); SWAP_IF_GREATER(x[5],x[13]); SWAP_IF_GREATER(x[6],x[14]); SWAP_IF_GREATER(x[7],x[15]); SWAP_IF_GREATER(x[16],x[24]);
  SWAP_IF_GREATER(x[17],x[25]); SWAP_IF_GREATER(x[18],x[26]); SWAP_IF_GREATER(x[19],x[27]); SWAP_IF_GREATER(x[20],x[28]); SWAP_IF_GREATER(x[21],x[29]); SWAP_IF_GREATER(x[22],x[30]);
  SWAP_IF_GREATER(x[0],x[16]); SWAP_IF_GREATER(x[1],x[8]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[12]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[6],x[9]);
  SWAP_IF_GREATER(x[7],x[14]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[17],x[24]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[19],x[28]); SWAP_IF_GREATER(x[21],x[26]);
  SWAP_IF_GREATER(x[22],x[25]); SWAP_IF_GREATER(x[23],x[30]); SWAP_IF_GREATER(x[27],x[29]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[8]);
  SWAP_IF_GREATER(x[6],x[22]); SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[9],x[25]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[17],x[18]);
  SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[20],x[24]); SWAP_IF_GREATER(x[23],x[27]); SWAP_IF_GREATER(x[26],x[28]); SWAP_IF_GREATER(x[29],x[30]); SWAP_IF_GREATER(x[1],x[17]);
  SWAP_IF_GREATER(x[2],x[18]); SWAP_IF_GREATER(x[3],x[19]); SWAP_IF_GREATER(x[4],x[20]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[7],x[23]); SWAP_IF_GREATER(x[8],x[24]);
  SWAP_IF_GREATER(x[11],x[27]); SWAP_IF_GREATER(x[12],x[28]); SWAP_IF_GREATER(x[13],x[29]); SWAP_IF_GREATER(x[14],x[30]); SWAP_IF_GREATER(x[21],x[26]); SWAP_IF_GREATER(x[3],x[17]);
  SWAP_IF_GREATER(x[4],x[16]); SWAP_IF_GREATER(x[5],x[21]); SWAP_IF_GREATER(x[6],x[18]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[8],x[20]); SWAP_IF_GREATER(x[10],x[26]);
  SWAP_IF_GREATER(x[11],x[23]); SWAP_IF_GREATER(x[13],x[25]); SWAP_IF_GREATER(x[14],x[28]); SWAP_IF_GREATER(x[15],x[27]); SWAP_IF_GREATER(x[22],x[24]); SWAP_IF_GREATER(x[1],x[4]);
  SWAP_IF_GREATER(x[3],x[8]); SWAP_IF_GREATER(x[5],x[16]); SWAP_IF_GREATER(x[7],x[17]); SWAP_IF_GREATER(x[9],x[21]); SWAP_IF_GREATER(x[10],x[22]); SWAP_IF_GREATER(x[11],x[19]);
  SWAP_IF_GREATER(x[12],x[20]); SWAP_IF_GREATER(x[14],x[24]); SWAP_IF_GREATER(x[15],x[26]); SWAP_IF_GREATER(x[23],x[28]); SWAP_IF_GREATER(x[27],x[30]); SWAP_IF_GREATER(x[2],x[5]);
  SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[18]); SWAP_IF_GREATER(x[11],x[17]); SWAP_IF_GREATER(x[12],x[16]); SWAP_IF_GREATER(x[13],x[22]); SWAP_IF_GREATER(x[14],x[20]);
  SWAP_IF_GREATER(x[15],x[19]); SWAP_IF_GREATER(x[23],x[24]); SWAP_IF_GREATER(x[26],x[29]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[6],x[12]); SWAP_IF_GREATER(x[9],x[16]);
  SWAP_IF_GREATER(x[10],x[11]); SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[14],x[18]); SWAP_IF_GREATER(x[15],x[22]); SWAP_IF_GREATER(x[19],x[25]); SWAP_IF_GREATER(x[20],x[21]);
  SWAP_IF_GREATER(x[27],x[29]); SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[14],x[16]);
  SWAP_IF_GREATER(x[15],x[17]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[19],x[23]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[25],x[26]); SWAP_IF_GREATER(x[3],x[5]);
  SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[15],x[18]);
  SWAP_IF_GREATER(x[17],x[20]); SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[22],x[23]); SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[26],x[28]); SWAP_IF_GREATER(x[3],x[4]);
  SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]);
  SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[23],x[24]); SWAP_IF_GREATER(x[25],x[26]); SWAP_IF_GREATER(x[27],x[28]);
}

template <typename T>
inline void sort_net_32(T* x) { // 185 comparators (Dobbelaere)
  SWAP_IF_GREATER(x[0],x[1]); SWAP_IF_GREATER(x[2],x[3]); SWAP_IF_GREATER(x[4],x[5]); SWAP_IF_GREATER(x[6],x[7]); SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[12],x[13]); SWAP_IF_GREATER(x[14],x[15]); SWAP_IF_GREATER(x[16],x[17]); SWAP_IF_GREATER(x[18],x[19]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[22],x[23]);
  SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[26],x[27]); SWAP_IF_GREATER(x[28],x[29]); SWAP_IF_GREATER(x[30],x[31]); SWAP_IF_GREATER(x[0],x[2]); SWAP_IF_GREATER(x[1],x[3]);
  SWAP_IF_GREATER(x[4],x[6]); SWAP_IF_GREATER(x[5],x[7]); SWAP_IF_GREATER(x[8],x[10]); SWAP_IF_GREATER(x[9],x[11]); SWAP_IF_GREATER(x[12],x[14]); SWAP_IF_GREATER(x[13],x[15]);
  SWAP_IF_GREATER(x[16],x[18]); SWAP_IF_GREATER(x[17],x[19]); SWAP_IF_GREATER(x[20],x[22]); SWAP_IF_GREATER(x[21],x[23]); SWAP_IF_GREATER(x[24],x[26]); SWAP_IF_GREATER(x[25],x[27]);
  SWAP_IF_GREATER(x[28],x[30]); SWAP_IF_GREATER(x[29],x[31]); SWAP_IF_GREATER(x[0],x[4]); SWAP_IF_GREATER(x[1],x[5]); SWAP_IF_GREATER(x[2],x[6]); SWAP_IF_GREATER(x[3],x[7]);
  SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[13]); SWAP_IF_GREATER(x[10],x[14]); SWAP_IF_GREATER(x[11],x[15]); SWAP_IF_GREATER(x[16],x[20]); SWAP_IF_GREATER(x[17],x[21]);
  SWAP_IF_GREATER(x[18],x[22]); SWAP_IF_GREATER(x[19],x[23]); SWAP_IF_GREATER(x[24],x[28]); SWAP_IF_GREATER(x[25],x[29]); SWAP_IF_GREATER(x[26],x[30]); SWAP_IF_GREATER(x[27],x[31]);
  SWAP_IF_GREATER(x[0],x[8]); SWAP_IF_GREATER(x[1],x[9]); SWAP_IF_GREATER(x[2],x[10]); SWAP_IF_GREATER(x[3],x[11]); SWAP_IF_GREATER(x[4],x[12]); SWAP_IF_GREATER(x[5],x[13]);
  SWAP_IF_GREATER(x[6],x[14]); SWAP_IF_GREATER(x[7],x[15]); SWAP_IF_GREATER(x[16],x[24]); SWAP_IF_GREATER(x[17],x[25]); SWAP_IF_GREATER(x[18],x[26]); SWAP_IF_GREATER(x[19],x[27]);
  SWAP_IF_GREATER(x[20],x[28]); SWAP_IF_GREATER(x[21],x[29]); SWAP_IF_GREATER(x[22],x[30]); SWAP_IF_GREATER(x[23],x[31]); SWAP_IF_GREATER(x[0],x[16]); SWAP_IF_GREATER(x[1],x[8]);
  SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[3],x[12]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[6],x[9]); SWAP_IF_GREATER(x[7],x[14]); SWAP_IF_GREATER(x[11],x[13]);
  SWAP_IF_GREATER(x[15],x[31]); SWAP_IF_GREATER(x[17],x[24]); SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[19],x[28]); SWAP_IF_GREATER(x[21],x[26]); SWAP_IF_GREATER(x[22],x[25]);
  SWAP_IF_GREATER(x[23],x[30]); SWAP_IF_GREATER(x[27],x[29]); SWAP_IF_GREATER(x[1],x[2]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[4],x[8]); SWAP_IF_GREATER(x[6],x[22]);
  SWAP_IF_GREATER(x[7],x[11]); SWAP_IF_GREATER(x[9],x[25]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[17],x[18]); SWAP_IF_GREATER(x[19],x[21]);
  SWAP_IF_GREATER(x[20],x[24]); SWAP_IF_GREATER(x[23],x[27]); SWAP_IF_GREATER(x[26],x[28]); SWAP_IF_GREATER(x[29],x[30]); SWAP_IF_GREATER(x[1],x[17]); SWAP_IF_GREATER(x[2],x[18]);
  SWAP_IF_GREATER(x[3],x[19]); SWAP_IF_GREATER(x[4],x[20]); SWAP_IF_GREATER(x[5],x[10]); SWAP_IF_GREATER(x[7],x[23]); SWAP_IF_GREATER(x[8],x[24]); SWAP_IF_GREATER(x[11],x[27]);
  SWAP_IF_GREATER(x[12],x[28]); SWAP_IF_GREATER(x[13],x[29]); SWAP_IF_GREATER(x[14],x[30]); SWAP_IF_GREATER(x[21],x[26]); SWAP_IF_GREATER(x[3],x[17]); SWAP_IF_GREATER(x[4],x[16]);
  SWAP_IF_GREATER(x[5],x[21]); SWAP_IF_GREATER(x[6],x[18]); SWAP_IF_GREATER(x[7],x[9]); SWAP_IF_GREATER(x[8],x[20]); SWAP_IF_GREATER(x[10],x[26]); SWAP_IF_GREATER(x[11],x[23]);
  SWAP_IF_GREATER(x[13],x[25]); SWAP_IF_GREATER(x[14],x[28]); SWAP_IF_GREATER(x[15],x[27]); SWAP_IF_GREATER(x[22],x[24]); SWAP_IF_GREATER(x[1],x[4]); SWAP_IF_GREATER(x[3],x[8]);
  SWAP_IF_GREATER(x[5],x[16]); SWAP_IF_GREATER(x[7],x[17]); SWAP_IF_GREATER(x[9],x[21]); SWAP_IF_GREATER(x[10],x[22]); SWAP_IF_GREATER(x[11],x[19]); SWAP_IF_GREATER(x[12],x[20]);
  SWAP_IF_GREATER(x[14],x[24]); SWAP_IF_GREATER(x[15],x[26]); SWAP_IF_GREATER(x[23],x[28]); SWAP_IF_GREATER(x[27],x[30]); SWAP_IF_GREATER(x[2],x[5]); SWAP_IF_GREATER(x[7],x[8]);
  SWAP_IF_GREATER(x[9],x[18]); SWAP_IF_GREATER(x[11],x[17]); SWAP_IF_GREATER(x[12],x[16]); SWAP_IF_GREATER(x[13],x[22]); SWAP_IF_GREATER(x[14],x[20]); SWAP_IF_GREATER(x[15],x[19]);
  SWAP_IF_GREATER(x[23],x[24]); SWAP_IF_GREATER(x[26],x[29]); SWAP_IF_GREATER(x[2],x[4]); SWAP_IF_GREATER(x[6],x[12]); SWAP_IF_GREATER(x[9],x[16]); SWAP_IF_GREATER(x[10],x[11]);
  SWAP_IF_GREATER(x[13],x[17]); SWAP_IF_GREATER(x[14],x[18]); SWAP_IF_GREATER(x[15],x[22]); SWAP_IF_GREATER(x[19],x[25]); SWAP_IF_GREATER(x[20],x[21]); SWAP_IF_GREATER(x[27],x[29]);
  SWAP_IF_GREATER(x[5],x[6]); SWAP_IF_GREATER(x[8],x[12]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[13]); SWAP_IF_GREATER(x[14],x[16]); SWAP_IF_GREATER(x[15],x[17]);
  SWAP_IF_GREATER(x[18],x[20]); SWAP_IF_GREATER(x[19],x[23]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[25],x[26]); SWAP_IF_GREATER(x[3],x[5]); SWAP_IF_GREATER(x[6],x[7]);
  SWAP_IF_GREATER(x[8],x[9]); SWAP_IF_GREATER(x[10],x[12]); SWAP_IF_GREATER(x[11],x[14]); SWAP_IF_GREATER(x[13],x[16]); SWAP_IF_GREATER(x[15],x[18]); SWAP_IF_GREATER(x[17],x[20]);
  SWAP_IF_GREATER(x[19],x[21]); SWAP_IF_GREATER(x[22],x[23]); SWAP_IF_GREATER(x[24],x[25]); SWAP_IF_GREATER(x[26],x[28]); SWAP_IF_GREATER(x[3],x[4]); SWAP_IF_GREATER(x[5],x[6]);
  SWAP_IF_GREATER(x[7],x[8]); SWAP_IF_GREATER(x[9],x[10]); SWAP_IF_GREATER(x[11],x[12]); SWAP_IF_GREATER(x[13],x[14]); SWAP_IF_GREATER(x[15],x[16]); SWAP_IF_GREATER(x[17],x[18]);
  SWAP_IF_GREATER(x[19],x[20]); SWAP_IF_GREATER(x[21],x[22]); SWAP_IF_GREATER(x[23],x[24]); SWAP_IF_GREATER(x[25],x[26]); SWAP_IF_GREATER(x[27],x[28]);
}

// NBIS: branchless insertion sort.
// All comparisons compile to MINSD/MAXSD — no data-dependent branches,
// no mispredictions. O(n²) but dominates std::sort for n <= ~64 because
// the misprediction cost of introsort's partitioning exceeds NBIS's
// O(n²) branchless comparisons when everything fits in L1 cache.
template <typename T>
inline void nbis_sort(T* x, int n) {
  for (int i = 1; i < n; ++i) {
    T v = x[i];
    for (int j = i; j > 0; --j) {
      T lo = (std::min)(v, x[j - 1]);
      T hi = (std::max)(v, x[j - 1]);
      x[j - 1] = lo;
      x[j]     = hi;
      v = lo;
    }
  }
}

// Dispatcher: use sorting networks for n<=16, nbis_sort for n>16
template <typename T>
inline void small_sort(T* x, size_t n) {
  switch (n) {
    case 0:
    case 1:
      return;
    case 2:
      sort_net_2(x);
      return;
    case 3:
      sort_net_3(x);
      return;
    case 4:
      sort_net_4(x);
      return;
    case 5:
      sort_net_5(x);
      return;
    case 6:
      sort_net_6(x);
      return;
    case 7:
      sort_net_7(x);
      return;
    case 8:
      sort_net_8(x);
      return;
    case 9:
      sort_net_9(x);
      return;
    case 10:
      sort_net_10(x);
      return;
    case 11:
      sort_net_11(x);
      return;
    case 12:
      sort_net_12(x);
      return;
    case 13:
      sort_net_13(x);
      return;
    case 14:
      sort_net_14(x);
      return;
    case 15:
      sort_net_15(x);
      return;
    case 16:
      sort_net_16(x);
      return;
    case 17:
      sort_net_17(x);
      return;
    case 18:
      sort_net_18(x);
      return;
    case 19:
      sort_net_19(x);
      return;
    case 20:
      sort_net_20(x);
      return;
    case 21:
      sort_net_21(x);
      return;
    case 22:
      sort_net_22(x);
      return;
    case 23:
      sort_net_23(x);
      return;
    case 24:
      sort_net_24(x);
      return;
    case 25:
      sort_net_25(x);
      return;
    case 26:
      sort_net_26(x);
      return;
    case 27:
      sort_net_27(x);
      return;
    case 28:
      sort_net_28(x);
      return;
    case 29:
      sort_net_29(x);
      return;
    case 30:
      sort_net_30(x);
      return;
    case 31:
      sort_net_31(x);
      return;
    case 32:
      sort_net_32(x);
      return;
    default:
      nbis_sort(x, (int)n);
      return;
  }
}

#undef SWAP_IF_GREATER

} // namespace robscale

#endif // ROBSCALE_SORT_NET_H
