# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adm_impl <- function(x, center, constant) {
    .Call(`_robscale_adm_impl`, x, center, constant)
}

adm_impl_auto <- function(x, constant) {
    .Call(`_robscale_adm_impl_auto`, x, constant)
}

C_adm_orig <- function(x) {
    .Call(`_robscale_C_adm_orig`, x)
}

C_adm_fast <- function(x) {
    .Call(`_robscale_C_adm_fast`, x)
}

C_adm_core_sorted <- function(x) {
    .Call(`_robscale_C_adm_core_sorted`, x)
}

rob_scale_diag_impl <- function(x_r, maxit = 80L, tol = 1.4901161193847656e-8) {
    .Call(`_robscale_rob_scale_diag_impl`, x_r, maxit, tol)
}

bench_median_net_impl <- function(x) {
    .Call(`_robscale_bench_median_net_impl`, x)
}

bench_fr_select_impl <- function(x) {
    .Call(`_robscale_bench_fr_select_impl`, x)
}

cpp_scale_ensemble <- function(x, n_boot) {
    .Call(`_robscale_cpp_scale_ensemble`, x, n_boot)
}

cpp_scale_ensemble_ci <- function(x, n_boot, level, method_code) {
    .Call(`_robscale_cpp_scale_ensemble_ci`, x, n_boot, level, method_code)
}

C_sn_sorted <- function(x) {
    .Call(`_robscale_C_sn_sorted`, x)
}

C_qn_sorted <- function(x) {
    .Call(`_robscale_C_qn_sorted`, x)
}

gmd_impl <- function(x, constant) {
    .Call(`_robscale_gmd_impl`, x, constant)
}

iqr_impl <- function(x, constant) {
    .Call(`_robscale_iqr_impl`, x, constant)
}

mad_impl_auto <- function(x, constant) {
    .Call(`_robscale_mad_impl_auto`, x, constant)
}

mad_impl_center <- function(x, center, constant) {
    .Call(`_robscale_mad_impl_center`, x, center, constant)
}

C_qn_fast <- function(x) {
    .Call(`_robscale_C_qn_fast`, x)
}

C_qn_int_fast <- function(x) {
    .Call(`_robscale_C_qn_int_fast`, x)
}

get_qnsn_config <- function() {
    .Call(`_robscale_get_qnsn_config`)
}

C_get_qn_factor <- function(n) {
    .Call(`_robscale_C_get_qn_factor`, n)
}

rob_loc_impl <- function(x, has_scale, scale_val, maxit, tol) {
    .Call(`_robscale_rob_loc_impl`, x, has_scale, scale_val, maxit, tol)
}

rob_loc_scalar_impl <- function(x) {
    .Call(`_robscale_rob_loc_scalar_impl`, x)
}

rob_loc_has_parallel <- function() {
    .Call(`_robscale_rob_loc_has_parallel`)
}

rob_loc_serial_impl <- function(x) {
    .Call(`_robscale_rob_loc_serial_impl`, x)
}

rob_scale_impl <- function(x, has_loc, loc_val, implbound, maxit, tol, fallback) {
    .Call(`_robscale_rob_scale_impl`, x, has_loc, loc_val, implbound, maxit, tol, fallback)
}

C_rob_scale_fast <- function(x) {
    .Call(`_robscale_C_rob_scale_fast`, x)
}

sd_c4_impl <- function(x) {
    .Call(`_robscale_sd_c4_impl`, x)
}

C_sn_fast <- function(x) {
    .Call(`_robscale_C_sn_fast`, x)
}

C_sn_int_fast <- function(x) {
    .Call(`_robscale_C_sn_int_fast`, x)
}

C_get_sn_factor <- function(n) {
    .Call(`_robscale_C_get_sn_factor`, n)
}

