# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adm_impl <- function(x, center, constant) {
    .Call(`_robscale_adm_impl`, x, center, constant)
}

adm_impl_auto <- function(x, constant) {
    .Call(`_robscale_adm_impl_auto`, x, constant)
}

rob_loc_impl <- function(x, has_scale, scale_val, maxit, tol) {
    .Call(`_robscale_rob_loc_impl`, x, has_scale, scale_val, maxit, tol)
}

rob_scale_impl <- function(x, has_loc, loc_val, implbound, maxit, tol) {
    .Call(`_robscale_rob_scale_impl`, x, has_loc, loc_val, implbound, maxit, tol)
}

